import type { IPost } from "@/models/post.model";

/**
 * 30 Dummy blog posts for seeding the database.
 * These are omitting _id, createdAt, and updatedAt as they will be generated by MongoDB.
 */
export const DUMMY_POSTS: Omit<
  IPost,
  "slug" | "_id" | "createdAt" | "updatedAt" | "coverText"
>[] = [
  {
    title: "Building scalable APIs with Node.js",
    excerpt:
      "Learn how to architect high-performance APIs that can handle millions of requests. In this guide, we explore clustering, caching strategies, and database optimization.",
    content: `# Building Scalable APIs with Node.js

APIs are the backbone of modern applications. When your user base grows, your API needs to grow with it.

## Clustering for Performance

Node.js is single-threaded, but we can leverage multiple cores using the cluster module. Here's how:

\`\`\`javascript
const cluster = require('cluster');
const os = require('os');

if (cluster.isMaster) {
  const numCPUs = os.cpus().length;
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }
}
\`\`\`

## Caching Strategy

Use Redis to cache frequently accessed data. This reduces database load and improves response times significantly.

## Database Optimization

- Add proper indexes on frequently queried fields
- Use pagination for large datasets
- Implement connection pooling

Start small, measure, then scale.`,
    cover: "blue",
    tags: ["nodejs", "api", "performance"],
    status: "published",
    featured: true,
    likes: 142,
    views: 856,
    readingTime: 5,
  },
  {
    title: "React 19 Server Components explained",
    excerpt:
      "React 19 introduces Server Components that run only on the server. Discover how they improve performance and enable new patterns.",
    content: `# React 19 Server Components Explained

Server Components are a paradigm shift in how we build React applications.

## What are Server Components?

They render only on the server and send HTML to the client. This means no JavaScript shipped for these components.

## Benefits

- Reduced bundle size
- Direct database access
- Better security
- Improved performance

## When to Use

Use Server Components for:
- Data fetching
- Accessing secure credentials
- Large dependencies

Use Client Components for:
- Interactivity
- Event listeners
- Browser APIs

The future is hybrid rendering.`,
    cover: "violet",
    tags: ["react", "nextjs", "performance"],
    status: "published",
    featured: true,
    likes: 187,
    views: 1230,
    readingTime: 6,
  },
  {
    title: "CSS Grid vs Flexbox - when to use what",
    excerpt:
      "Both CSS Grid and Flexbox are powerful layout tools. Understanding their differences helps you choose the right tool for the job.",
    content: `# CSS Grid vs Flexbox - When to Use What

Layout is fundamental to web design. Let's compare the two modern approaches.

## Flexbox Basics

Flexbox is one-dimensional. It arranges items in a row or column.

Perfect for:
- Navigation bars
- Button groups
- Content alignment

## Grid Basics

Grid is two-dimensional. It creates rows and columns simultaneously.

Perfect for:
- Page layouts
- Complex designs
- Responsive grids

## A Simple Rule

- Flexbox: linear layouts
- Grid: bidimensional layouts

Use both together for maximum flexibility.`,
    cover: "green",
    tags: ["css", "layout", "design"],
    status: "published",
    featured: false,
    likes: 98,
    views: 654,
    readingTime: 4,
  },
  {
    title: "TypeScript generics for beginners",
    excerpt:
      "Generics are powerful but intimidating. This guide breaks them down into digestible concepts with practical examples.",
    content: `# TypeScript Generics for Beginners

Generics enable code reusability while maintaining type safety.

## Basic Generic Function

\`\`\`typescript
function identity<T>(arg: T): T {
  return arg;
}
\`\`\`

Here T is a type variable that will be inferred from usage.

## Generic Constraints

You can restrict what types a generic can accept:

\`\`\`typescript
function getProperty<T, K extends keyof T>(obj: T, key: K) {
  return obj[key];
}
\`\`\`

## Real-World Example

\`\`\`typescript
interface API<T> {
  data: T[];
  status: 'success' | 'error';
}
\`\`\`

Generics are about writing flexible, reusable code.`,
    cover: "indigo",
    tags: ["typescript", "javascript"],
    status: "published",
    featured: false,
    likes: 76,
    views: 432,
    readingTime: 5,
  },
  {
    title: "Authentication flows - JWT vs Sessions",
    excerpt:
      "Choosing between JWT and session-based authentication? Let's explore the tradeoffs and pick the right approach for your app.",
    content: `# Authentication Flows - JWT vs Sessions

Security is non-negotiable. Let's understand two main approaches.

## Session-Based Authentication

The server creates a session and stores it. The client gets a session ID in a cookie.

Pros:
- Easy to revoke
- Stateful, so server has control
- Built-in CSRF protection

Cons:
- Requires server-side storage
- Harder to scale across servers

## JWT Authentication

The server signs a token with a secret. The client stores and sends it with each request.

Pros:
- Stateless
- Scales easily
- Self-contained

Cons:
- Harder to revoke
- Token size can be large
- Requires secure storage

## The Verdict

For most applications, hybrid approach works best:
- Use JWT for API access
- Use refresh tokens with short expiry
- Store tokens securely

Pick based on your scale and requirements.`,
    cover: "pink",
    tags: ["authentication", "security", "backend"],
    status: "published",
    featured: false,
    likes: 134,
    views: 789,
    readingTime: 6,
  },
  {
    title: "Web performance optimization tips",
    excerpt:
      "Fast websites convert better. Learn practical techniques to measure and improve your site's performance metrics.",
    content: `# Web Performance Optimization Tips

Performance is a feature. Here's how to ship fast.

## Core Web Vitals

Google's metrics for user experience:

1. **LCP** - Largest Contentful Paint (< 2.5s)
2. **FID** - First Input Delay (< 100ms)
3. **CLS** - Cumulative Layout Shift (< 0.1)

## Practical Optimizations

### Image Optimization
- Use modern formats (WebP)
- Implement lazy loading
- Serve responsive images

### Code Splitting
Split your bundle. Load only what's needed per route.

### Caching Strategy
- Browser caching for static assets
- CDN for global distribution
- Service Workers for offline support

## Tools

- Lighthouse for auditing
- Web Vitals library for monitoring
- Bundle analyzers for size insights

Measure first, then optimize.`,
    cover: "orange",
    tags: ["performance", "optimization", "frontend"],
    status: "published",
    featured: false,
    likes: 156,
    views: 921,
    readingTime: 7,
  },
  {
    title: "Understanding JavaScript closures",
    excerpt:
      "Closures are one of JavaScript's most powerful features. Master them and level up your programming skills.",
    content: `# Understanding JavaScript Closures

Closures are functions that have access to variables from their outer scope.

## Basic Example

\`\`\`javascript
function outer() {
  let count = 0;
  
  return function inner() {
    count++;
    console.log(count);
  };
}

const counter = outer();
counter(); // 1
counter(); // 2
\`\`\`

The inner function "closes over" the count variable.

## Real-World Uses

### Data Privacy
\`\`\`javascript
const createBankAccount = (initial) => {
  let balance = initial;
  
  return {
    deposit: (amount) => balance += amount,
    withdraw: (amount) => balance -= amount,
    getBalance: () => balance,
  };
};
\`\`\`

### Callbacks and Async
Closures are essential for callbacks, promises, and async-await patterns.

Closures enable powerful patterns in JavaScript.`,
    cover: "blue",
    tags: ["javascript", "closure"],
    status: "published",
    featured: false,
    likes: 89,
    views: 567,
    readingTime: 4,
  },
  {
    title: "Mobile-first design principles",
    excerpt:
      "Design for the smallest screen first. Discover why mobile-first is the modern standard and how to implement it.",
    content: `# Mobile-First Design Principles

Mobile-first design isn't just about phones. It's about prioritizing the user's needs.

## Why Mobile-First?

- 60%+ of web traffic is mobile
- Forces prioritization of features
- Progressive enhancement works better
- Better performance constraints

## Implementation Strategy

Start with mobile CSS, then use media queries for larger screens:

\`\`\`css
/* Mobile first */
.container {
  padding: 1rem;
  font-size: 14px;
}

/* Tablet and up */
@media (min-width: 768px) {
  .container {
    padding: 2rem;
    font-size: 16px;
  }
}

/* Desktop and up */
@media (min-width: 1024px) {
  .container {
    max-width: 1200px;
  }
}
\`\`\`

## Touch-Friendly Design

- Buttons at least 44x44px
- Adequate spacing between interactive elements
- Large enough text for comfortable reading

Mobile-first leads to better experiences for everyone.`,
    cover: "violet",
    tags: ["design", "mobile", "responsive"],
    status: "published",
    featured: false,
    likes: 112,
    views: 678,
    readingTime: 5,
  },
  {
    title: "Testing strategies for modern web apps",
    excerpt:
      "Unit tests, integration tests, and E2E tests each have their place. Learn how to balance them for maximum coverage with minimal flakiness.",
    content: `# Testing Strategies for Modern Web Apps

Testing is your safety net. Let's build a solid testing strategy.

## The Testing Pyramid

### Unit Tests (Base)
Test individual functions in isolation. Fast and focused.

\`\`\`javascript
test('adds two numbers', () => {
  expect(add(2, 3)).toBe(5);
});
\`\`\`

### Integration Tests (Middle)
Test how components work together.

### E2E Tests (Top)
Test the entire user flow. Slow but most realistic.

## Best Practices

- Write tests that describe behavior, not implementation
- Aim for 70-80% coverage
- Prioritize critical user paths
- Use mocking to isolate units
- Keep tests fast and deterministic

## Tools

- Jest for unit testing
- React Testing Library for components
- Playwright for E2E

Good tests give you confidence to refactor.`,
    cover: "green",
    tags: ["testing", "quality", "javascript"],
    status: "published",
    featured: false,
    likes: 98,
    views: 543,
    readingTime: 6,
  },
  {
    title: "Building accessible web applications",
    excerpt:
      "Accessibility isn't an afterthought. Learn how to build inclusive apps that work for everyone from day one.",
    content: `# Building Accessible Web Applications

Accessibility is about inclusion. Let's build for everyone.

## WCAG Guidelines

The Web Content Accessibility Guidelines define standards:

- **A** - Basic accessibility
- **AA** - Enhanced accessibility (recommended)
- **AAA** - Advanced accessibility

## Key Principles

### Perceivable
Content must be perceptible to users. Use alt text for images.

\`\`\`html
<img src="logo.png" alt="Company logo">
\`\`\`

### Operable
Users must be able to navigate with keyboard.

### Understandable
Content and interactions must be clear.

### Robust
Code must work with assistive technologies.

## Practical Tips

- Use semantic HTML
- Test with screen readers
- Ensure color contrast ratios (4.5:1 for text)
- Provide keyboard navigation
- Use ARIA when necessary

Accessibility benefits everyone, not just people with disabilities.`,
    cover: "indigo",
    tags: ["accessibility", "inclusion", "frontend"],
    status: "published",
    featured: false,
    likes: 145,
    views: 812,
    readingTime: 7,
  },
  {
    title: "Next.js caching mental model",
    excerpt:
      "Cache Components, use cache, and revalidation explained with simple rules you can actually remember.",
    content: `# Next.js Caching Mental Model

Caching in Next.js feels complex until you learn the core idea.

## The Core Rule

- Static by default, dynamic when you use runtime data.
- "use cache" marks a function result as cacheable.
- Revalidate with tags when data changes.

## Practical Setup

Cache reads with a tag like "posts", then call revalidateTag("posts") on writes.

Keep it simple: cache lists, revalidate on mutation.`,
    cover: "violet",
    tags: ["nextjs", "react", "caching"],
    status: "published",
    featured: true,
    likes: 178,
    views: 1104,
    readingTime: 5,
  },
  {
    title: "PostgreSQL indexes that matter",
    excerpt:
      "B-tree, GIN, and partial indexes with real examples of when each one saves your queries.",
    content: `# PostgreSQL Indexes That Matter

Most slow queries are fixed with the right index.

## B-tree Is the Default

Great for equality and range queries on sortable columns.

## GIN for Arrays and JSON

Use GIN when you query inside arrays or JSONB fields.

## Partial Indexes

Index only the rows you query often, like active users.

Measure with EXPLAIN ANALYZE before and after.`,
    cover: "blue",
    tags: ["postgres", "database", "backend"],
    status: "published",
    featured: false,
    likes: 121,
    views: 743,
    readingTime: 6,
  },
  {
    title: "Docker for local development",
    excerpt:
      "A minimal Docker setup for databases and services without slowing down your machine.",
    content: `# Docker for Local Development

Docker shines for local services like Postgres and Redis.

## Keep It Minimal

One compose file, only the services you need. Mount volumes for data persistence.

## Useful Commands

- docker compose up -d for background services
- docker compose down to stop everything
- docker logs for debugging

Your app code stays native, services stay isolated.`,
    cover: "green",
    tags: ["docker", "devops", "backend"],
    status: "published",
    featured: false,
    likes: 87,
    views: 512,
    readingTime: 4,
  },
  {
    title: "Git workflows that scale",
    excerpt:
      "Trunk-based development vs GitFlow, plus a simple branching strategy for small teams.",
    content: `# Git Workflows That Scale

Small teams do best with simple workflows.

## Trunk-Based Development

Short-lived branches, merge to main daily, release from main.

## When GitFlow Helps

Long release cycles with versioned releases benefit from release branches.

## The Basics That Matter

- Small commits with clear messages
- Pull requests with review
- CI running tests on every push

Ship small, ship often.`,
    cover: "orange",
    tags: ["git", "workflow", "engineering"],
    status: "published",
    featured: false,
    likes: 93,
    views: 598,
    readingTime: 5,
  },
  {
    title: "REST API design checklist",
    excerpt:
      "Naming, status codes, pagination, and versioning - a practical checklist for clean APIs.",
    content: `# REST API Design Checklist

Good APIs are predictable. Follow these rules.

## Resources and Verbs

- Nouns for resources: /posts, /users
- HTTP verbs for actions: GET, POST, PATCH, DELETE

## Status Codes

- 200 for success, 201 for created
- 400 for bad input, 404 for missing, 500 for server errors

## Pagination and Filtering

Use limit/offset or cursor pagination, and query params for filters.

Consistency beats cleverness.`,
    cover: "indigo",
    tags: ["api", "backend", "design"],
    status: "published",
    featured: false,
    likes: 104,
    views: 671,
    readingTime: 5,
  },
  {
    title: "State management without the mess",
    excerpt:
      "When to use local state, context, or a store like Zustand - with clear decision rules.",
    content: `# State Management Without the Mess

Most state problems come from putting state in the wrong place.

## The Decision Ladder

1. Local state first with useState
2. Shared UI state with context or a light store
3. Server state with fetch caching, not client stores

## Zustand for Simplicity

Small stores per concern beat one giant global store.

Keep server data out of client stores.`,
    cover: "pink",
    tags: ["react", "state", "frontend"],
    status: "published",
    featured: false,
    likes: 116,
    views: 702,
    readingTime: 5,
  },
  {
    title: "Writing useful error messages",
    excerpt:
      "Good errors tell users what happened and what to do next. Examples for forms, APIs, and CLIs.",
    content: `# Writing Useful Error Messages

Every error should answer two questions: what happened, and what now.

## The Formula

- Say what went wrong in plain words
- Say how to fix it or where to go next
- Never show raw stack traces to users

## Example

Bad: "Error 422". Good: "Email is already registered. Try signing in instead."

Clear errors reduce support tickets.`,
    cover: "violet",
    tags: ["ux", "writing", "frontend"],
    status: "published",
    featured: false,
    likes: 68,
    views: 389,
    readingTime: 3,
  },
  {
    title: "Intro to message queues",
    excerpt:
      "Why background jobs exist, and how queues like BullMQ keep your API fast under load.",
    content: `# Intro to Message Queues

Slow tasks do not belong in request handlers.

## What Goes to a Queue

- Sending emails
- Generating reports
- Image processing
- Webhook retries

## The Pattern

API enqueues a job and responds fast. Workers process jobs with retries.

Start with one queue, add more as you grow.`,
    cover: "blue",
    tags: ["backend", "queues", "architecture"],
    status: "published",
    featured: false,
    likes: 91,
    views: 534,
    readingTime: 5,
  },
  {
    title: "CSS variables for theming",
    excerpt:
      "Build light and dark themes with CSS variables instead of duplicated styles.",
    content: `# CSS Variables for Theming

Themes are just variable swaps.

## The Setup

Define tokens on :root, override them under .dark. Components reference variables, never raw colors.

## Why It Works

- One class toggle switches themes
- No duplicated component styles
- Easy to add more themes later

Tokens first, components second.`,
    cover: "green",
    tags: ["css", "theming", "design"],
    status: "published",
    featured: false,
    likes: 83,
    views: 467,
    readingTime: 4,
  },
  {
    title: "Monitoring with logs that help",
    excerpt:
      "Structured logging basics: what to log, what to skip, and how to find issues fast.",
    content: `# Monitoring With Logs That Help

Logs should answer questions, not create them.

## Log With Structure

JSON logs with level, message, request id, and duration beat plain text.

## What to Log

- Request start and finish with duration
- Errors with stack and context
- Key business events

## What to Skip

- Noisy debug logs in production
- Sensitive data like tokens

Use a custom logger, never raw console.log.`,
    cover: "orange",
    tags: ["observability", "backend", "devops"],
    status: "published",
    featured: false,
    likes: 74,
    views: 421,
    readingTime: 4,
  },
  {
    title: "Markdown writing workflow",
    excerpt:
      "How I draft in plain Markdown and publish to blog, newsletter, and RSS from one source.",
    content: `# Markdown Writing Workflow

One source, many outputs.

## The Setup

- Draft in Markdown files
- Preview with a Markdown editor
- Publish the same content to blog and newsletter

## Small Habits

- Short headings, short paragraphs
- One idea per post
- Write the excerpt first to clarify the point

Plain text keeps you focused on words.`,
    cover: "pink",
    tags: ["writing", "markdown", "workflow"],
    status: "published",
    featured: false,
    likes: 97,
    views: 583,
    readingTime: 4,
  },
  {
    title: "Rate limiting basics",
    excerpt:
      "Token bucket vs fixed window, plus simple rate limit headers your API should return.",
    content: `# Rate Limiting Basics

Rate limits protect your API from abuse and accidents.

## Common Strategies

- Fixed window: simple, can burst at edges
- Token bucket: smooths bursts, slightly more complex

## Headers to Return

- X-RateLimit-Limit for the quota
- X-RateLimit-Remaining for what is left

Start generous, tighten when you see abuse.`,
    cover: "indigo",
    tags: ["api", "security", "backend"],
    status: "published",
    featured: false,
    likes: 88,
    views: 496,
    readingTime: 4,
  },
  {
    title: "Responsive images made simple",
    excerpt:
      "Srcset, sizes, and modern formats - serve sharp images without wasting bandwidth.",
    content: `# Responsive Images Made Simple

Images are usually the heaviest part of a page.

## The Essentials

- Use WebP or AVIF with fallbacks
- Serve multiple widths with srcset
- Lazy load below-the-fold images

## Sizes Attribute

Tell the browser how wide the image renders so it picks the right file.

Smaller files, same sharp look.`,
    cover: "violet",
    tags: ["performance", "images", "frontend"],
    status: "published",
    featured: false,
    likes: 79,
    views: 445,
    readingTime: 4,
  },
  {
    title: "Code reviews that help",
    excerpt:
      "Review behavior first, style second. A short checklist for kind and useful reviews.",
    content: `# Code Reviews That Help

Good reviews make the code and the author better.

## Review Order

1. Correctness and edge cases
2. Readability and naming
3. Tests for critical paths
4. Style nitpicks last, or automate them

## Tone Matters

Ask questions instead of giving orders. Suggest, do not demand.

Automate formatting so humans discuss design.`,
    cover: "blue",
    tags: ["engineering", "teamwork", "quality"],
    status: "published",
    featured: false,
    likes: 71,
    views: 398,
    readingTime: 4,
  },
  {
    title: "Environment variables done right",
    excerpt:
      "Validate env at startup, keep secrets out of git, and document every variable.",
    content: `# Environment Variables Done Right

Missing env vars cause the worst production bugs.

## The Rules

- Validate on boot and fail fast with clear messages
- Never commit secrets, use .env.local
- Document each variable with an example

## Centralize Access

Export all env from one module like lib/env.ts so the rest of the app imports from there.

One source of truth for config.`,
    cover: "green",
    tags: ["config", "backend", "devops"],
    status: "published",
    featured: false,
    likes: 66,
    views: 372,
    readingTime: 3,
  },
  {
    title: "Pagination UX patterns",
    excerpt:
      "Numbered pages vs load more vs infinite scroll - when to use each one.",
    content: `# Pagination UX Patterns

Pagination shapes how users explore content.

## Numbered Pages

Best for archives where users jump around. Great for SEO.

## Load More

Best for casual browsing without losing scroll position.

## Infinite Scroll

Best for feeds, worst for footers and finding things again.

For blogs, numbered routes like /page/2 win.`,
    cover: "orange",
    tags: ["ux", "design", "frontend"],
    status: "published",
    featured: false,
    likes: 82,
    views: 459,
    readingTime: 4,
  },
  {
    title: "JSON APIs and validation with Zod",
    excerpt:
      "Validate every request at the boundary so your handlers only see clean data.",
    content: `# JSON APIs and Validation With Zod

Never trust client input.

## Validate at the Boundary

Parse request bodies with a schema before touching the database.

## The Payoff

- Clear 400 errors for bad input
- Type-safe handlers after parsing
- One place to update when shapes change

Schemas are documentation that runs.`,
    cover: "pink",
    tags: ["typescript", "validation", "backend"],
    status: "published",
    featured: true,
    likes: 133,
    views: 768,
    readingTime: 5,
  },
  {
    title: "Dark mode without headaches",
    excerpt:
      "Class-based dark mode with tokens, plus how to avoid flash of wrong theme.",
    content: `# Dark Mode Without Headaches

Dark mode is easy when tokens do the work.

## The Setup

- Toggle a .dark class on html
- Override CSS variables under .dark
- Persist choice in localStorage

## Avoiding Flash

Inline a tiny script that sets the class before first paint.

Tokens plus one class, no overrides everywhere.`,
    cover: "indigo",
    tags: ["css", "theming", "frontend"],
    status: "published",
    featured: false,
    likes: 108,
    views: 634,
    readingTime: 4,
  },
  {
    title: "Caching static assets",
    excerpt:
      "Content hashes, long cache headers, and CDN basics for fast repeat visits.",
    content: `# Caching Static Assets

Repeat visits should feel instant.

## The Trick

- Hash filenames so each build gets unique URLs
- Serve hashed files with long immutable cache headers
- Serve HTML with short or no cache

## CDN Layer

Put a CDN in front for global edge caching of static files.

Build once, serve fast everywhere.`,
    cover: "violet",
    tags: ["performance", "caching", "devops"],
    status: "published",
    featured: false,
    likes: 77,
    views: 433,
    readingTime: 4,
  },
  {
    title: "Writing git commit messages",
    excerpt:
      "Short subject, clear body, and why it matters more than you think.",
    content: `# Writing Git Commit Messages

Future you reads these messages. Be kind.

## The Format

- Subject under 50 chars in imperative mood
- Blank line, then body explaining why
- Reference issue numbers when relevant

## Example

"Add pagination to stories list" beats "fix stuff".

Clear history speeds up debugging.`,
    cover: "blue",
    tags: ["git", "workflow", "engineering"],
    status: "published",
    featured: false,
    likes: 59,
    views: 341,
    readingTime: 3,
  },
];
